# multi-LiDAR-GNSS calibration configurations
data:
    odometry: "/apollo/data/bag/calibration/export/2019-05-23-10-21-01/_apollo_sensor_gnss_odometry/odometry"
    lidars: 
        - velodyne64: 
            path: "/apollo/data/bag/calibration/export/2019-05-23-10-21-01/_apollo_sensor_velodyne64_PointCloud2/"
    result: "/apollo/data/bag/calibration/export/multi_lidar_gnss/result/"
calibration:
    init_extrinsics:
        velodyne64:
            translation:    
                x: 0.0
                y: 1.0508
                z: 1.1089
            rotation:
                x: 0
                y: 0
                z: 0.707
                w: 0.707
    steps: 
        - source_lidars: ["velodyne64"]
          target_lidars: ["velodyne64"]
          lidar_type: "multiple"
          fix_target_lidars: false
          fix_z: false
          iteration: 10
